### ISSUE TITLE
content پیشنهاد درمورد بخش

### ISSUE THREAD

**Issue by ahmadsalimi** [AdvProg2020/AdvProg2020.github.io#2]
<div dir="rtl">
یک سری پیشنهاد در مورد بخش
content
داشتم که در ادامه لیست کردم:

- [x] ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌  جاهایی که از badge با عنوان Preview استفاده شده، بنظرم بهتره از یه کلمه دیگه استفاده بشه، چون preview به معنی پیش‌نمایشه و خب اینجا معنی نداره زیاد. بنظرم بهتره مثلا بذاریم Video.
- [x] ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌  بنظرم بهتره به جای Excercise از Assignment استفاده کنیم، تو اکثر دانشگاهای دنیا از Assignment استفاده میشه بعنوان تمرین.
- [x] ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌  قرار بود به Quera هم لینک بدیم. بنظرم اون اولش بگیم که میتونین برای سابمیت کردن و جاج کردن جوابای تمرینتون تو کلاس کوئرا عضو بشین، و بعد کنار هر تمرین هم لینک بدیم به تمرین تو کوئرا برای سابمیت کردن.
- [x] ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌  در مورد استایل Collapse ای که استفاده شده، بنظرم برای این که خیلی شلوغ نشه صفحه، بهتره از حالتی که [اینجا](https://getbootstrap.com/docs/4.0/components/collapse/#accordion-example) گفته شده استفاده کنیم، که در نتیجه اگه یه tab دیگه رو باز کردیم، اونی که قبلا باز بوده اتوماتیک بسته بشه و اینجوری نشه همشون همزمان باز باشن.
- [x] ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌  تو بخش 0.2 واژه‌ی presented نوشته شده presnetd.
- [x] ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌  من یه کم حس خوبی از واژه‌ی Lesson نمی‌گیرم. البته ممکنه مشکل از من باشه ولی کلا جایگزین بهتری نمی‌تونیم داشته باشیم؟
</div>

**Comment by hamilamailee** [comment]
<div dir="rtl">

@ahmadsalimi 

- بخش اول حتما اعمال میشه
- در رابطه با بخش دوم من خودم بیشتر سعی کردم شبیه سایتایی مثل coursera بشه که اگه اشتباه نکنم اونا هم از Exercise استفاده میکنن (یا حالا practice). اگه به نظرت یکی از این دوتا مناسب نیست با assignment پیش میریم
-  لینک کوئرا رو هم میذارم برای جاج. در رابطه با جایی که باید گذاشته بشه هم، هم میتونیم رو به روی هر تمرین بذاریم با این توضیح که اونجا میتونن جاج شن یا اینکه اول همه ی درسا تو یه توضیحی راجع به کورس بگم که کلا تمرین ها میتونن جاج بشن. اینشو بگو
- استایل collapse رو هم درست میکنم مرسی
- در رابطه با کلمه lesson چند تا جایگزین داریم. دوباره میتونیم مثه coursera از چیزایی مثه week یا course استفاده کنیم ولی خب تعداد جلسه ها خیلی بیشترن. باز دنبال کلمه های جایگزین میکردم و هر چی پیدا کردم می پرسم.

ممنون

</div>

**Comment by ahmadsalimi** [comment]
<div dir="rtl">

- مورد دوم رو نکته‌ای ندارم روش، ولی چون به معنای واقعی تکلیف (Assignment) بوده، نه صرفا تمرین (Exercise) گفتم.
- مورد سوم، بنظرم اول کار بگیم که برید اینجا join بشید، بعد کنار هر تمرین، بگیم اینجا می‌تونید سابمیت کنید و نمره بگیرید. (دقیقا لینک تمرین رو بدیم که مستقیم بره تو تمرین)
- آخری هم چون خودم هم جایگزینی مدنظرم نیست همون Lesson اوکیه پس. البته مثلا Section میتونیم بذاریم ولی نمی‌دونم چقدر خوب می‌تونه باشه

@hamilamailee 

</div>
