### ISSUE TITLE
ایجاد قسمت دست اندرکاران

### ISSUE THREAD

**Issue by mhaghighat20** [AdvProg2020/AdvProg2020.github.io#4]
<div dir='rtl'>
پیشنهاد می کنم  قسمت دست اندر کاران به سایت اضافه بشه که عکس و مشخصات و نقش اون ها توی تیم دستیاران آموزشی رو داشته باشه

این کار دو تا خوبی داره اول این که یک جور تشکر از دستیاران آموزشی هست که این ترم فعالیت کردن و دوم این که ساختار تیم دستیاران آموزشی برای سال های آینده دانشگاه خودمون و دانشگاه های دیگه  به یادگار می مونه

به عنوان نمونه اینجا رو ببینین:

https://sauleh.github.io/ap97/

</div>

**Comment by ahmadsalimi** [comment]
اینجا پیشنهاد من اینه که از ساختاری شبیه به [این](https://bootsnipp.com/snippets/92xNm) استفاده کنیم

**Comment by ahmadsalimi** [comment]
از ساختار اسلایدر استفاده کنیم
https://codepen.io/jebbles/pen/MKoYya
