### ISSUE TITLE
ایجاد قسمت تجربه های ما

### ISSUE THREAD

**Issue by mhaghighat20** [AdvProg2020/AdvProg2020.github.io#5]
<div dir='rtl'>
به نظرم یک قسمت تجربه های ما اضافه بشه که توی اون لینک تمام مطالب ویرگول مرتبط با برنامه سازی پیشرفته رو اضافه کنیم

در حال حاضر مستند تمرین آماده شده و در لینک زیر هست:

https://vrgl.ir/WaSVv

</div>

**Comment by ahmadsalimi** [comment]
اینجا از [این](https://getbootstrap.com/docs/4.0/components/card/#example) ساختار می‌تونیم استفاده کنیم.
